useTabs: true
trailingComma: none
arrowParens: avoid
plugins:
  - prettier-plugin-svelte
pluginSearchDirs:
  - .
overrides:
  -
    files: "*.svelte"
    options:
      parser: svelte
importOrderSeparation: false
importOrderSortSpecifiers: true
